services: docker
sudo: required
env:
  DOCKER_COMPOSE_VERSION: 2

before_install:
  - sudo service mysql stop
  - sudo /etc/init.d/postgresql stop

script:
  - docker-compose build
  - docker-compose up -d
  - docker exec php-api  vendor/bin/phpunit tests  --verbose
  - docker exec php-api  chmod -R a+rw /var/cache/api/
  - docker exec php-api  chmod -R a+rw /var/log/api/
  - docker exec php-api  chmod -R a+rw /var/cache/api/  /var/log/api/
  - docker exec php-api  vendor/bin/behat
  - docker-compose kill
