version: "2"

services:
  web:
    build: .
    environment:
       XDEBUG_CONFIG: 'idekey=PHPSTORM'
       PHP_IDE_CONFIG: 'serverName=application'
       ENV: 'dev'
    container_name: php-api
    command: sh /srv/scripts/post_install_api.sh
    volumes:
       - ./:/srv
    working_dir: /srv/api
    ports:
      - 80:80
    networks:
      - back-tier


networks:
  back-tier: